// Local sync stub - data stored in localStorage
var Sync={myId:null,roomCode:null,myMood:null,partnerMood:null,partnerMessages:[],onChange:null,polling:null,
init:function(cb){this.onChange=cb},
joinRoom:function(code,name){var d=this._load();if(!d.user1||!d.user1.name){this.myId=1;d.user1={name:name,mood:{status:'sunny',updatedAt:new Date().toISOString()}}}else if(!d.user2||!d.user2.name){this.myId=2;d.user2={name:name,mood:{status:'sunny',updatedAt:new Date().toISOString()}}}else{this.myId=1;d.user1={name:name,mood:d.user1.mood||{status:'sunny',updatedAt:null}}}this.roomCode=code;localStorage.setItem('sync_roomCode',code);localStorage.setItem('sync_myId',String(this.myId));this._save(d);this._startPolling();if(this.onChange)this.onChange('ready')},
reconnect:function(cb){var c=localStorage.getItem('sync_roomCode');var i=localStorage.getItem('sync_myId');if(!c||!i)return false;this.roomCode=c;this.myId=parseInt(i);this.onChange=cb;this._startPolling();return true},
_startPolling:function(){var s=this;if(this.polling)clearInterval(this.polling);this._poll();this.polling=setInterval(function(){s._poll()},3000)},
_poll:function(){var d=this._load();if(d)this._process(d)},
_process:function(d){var ch=false,pi=this.myId===1?2:1,mk='user'+this.myId,pk='user'+pi;if(d[mk]&&d[mk].mood)this.myMood=d[mk].mood;if(d[pk]&&d[pk].mood){var pm=d[pk].mood;if(!this.partnerMood||this.partnerMood.updatedAt!==pm.updatedAt){this.partnerMood=pm;ch=true}}if(d.messages){for(var i=0;i<d.messages.length;i++){var m=d.messages[i];if(m.sender===pi){var ex=this.partnerMessages.some(function(x){return x.createdAt===m.createdAt});if(!ex){this.partnerMessages.unshift(m);ch=true}}}if(ch)this.partnerMessages.sort(function(a,b){return new Date(b.createdAt)-new Date(a.createdAt)})}if(ch&&this.onChange)this.onChange('mood')},
updateMood:function(s){var d=this._load();if(!d)return;var mk='user'+this.myId;if(!d[mk])d[mk]={name:'我'};d[mk].mood={status:s,updatedAt:new Date().toISOString()};this.myMood=d[mk].mood;this._save(d)},
sendMessage:function(t,dd,m){var s=this;return new Promise(function(r){var d=s._load();if(!d){r({error:'failed'});return}if(!d.messages)d.messages=[];d.messages.push({sender:s.myId,text:t||'',doodleDataUrl:dd||null,mood:m||'sunny',createdAt:new Date().toISOString()});if(d.messages.length>100)d.messages=d.messages.slice(-100);s._save(d);r({success:true})})},
_load:function(){try{var r=localStorage.getItem('sync_data');if(!r)return{user1:null,user2:null,messages:[]};return JSON.parse(r)}catch(e){return{user1:null,user2:null,messages:[]}}},
_save:function(d){try{localStorage.setItem('sync_data',JSON.stringify(d))}catch(e){}},
leave:function(){if(this.polling)clearInterval(this.polling);localStorage.removeItem('sync_roomCode');localStorage.removeItem('sync_myId');this.roomCode=null;this.myId=null}};
