// Supabase sync - real cross-device sync
var Sync={
myId:null,roomCode:null,myMood:null,partnerMood:null,partnerMessages:[],onChange:null,polling:null,
BASE:'https://dunadheorduiyxmfzlfu.supabase.co/rest/v1/sync_data',
KEY:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1bmFkaGVvcmR1aXl4bWZ6bGZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE4OTQ0ODksImV4cCI6MjA5NzQ3MDQ4OX0.s8a5FLcmYmHv-1IaidLnu_5VRxJf6JEvsl8u20MpZcA',
init:function(cb){this.onChange=cb},
joinRoom:function(code,name){var s=this;s.roomCode=code;var q='room_code=eq.'+encodeURIComponent(code);s._get(q,function(rows){if(rows&&rows.length){var d=rows[0];if(!d.user1_name){s.myId=1;d.user1_name=name;d.user1_mood={status:'sunny',updatedAt:new Date().toISOString()}}else if(!d.user2_name){s.myId=2;d.user2_name=name;d.user2_mood={status:'sunny',updatedAt:new Date().toISOString()}}else{s.myId=1;d.user1_name=name}s._patch(d.id,d,function(){s._saveLocal(code);s._startPolling();if(s.onChange)s.onChange('ready')})}else{var data={room_code:code,user1_name:name,user1_mood:{status:'sunny',updatedAt:new Date().toISOString()},user2_name:'',user2_mood:{status:'sunny',updatedAt:null},messages:[]};s.myId=1;s._post(data,function(r){s._saveLocal(code);s._startPolling();if(s.onChange)s.onChange('ready')})}})},
reconnect:function(cb){var c=localStorage.getItem('sync_roomCode');var i=localStorage.getItem('sync_myId');if(!c||!i)return false;this.roomCode=c;this.myId=parseInt(i);this.onChange=cb;this._startPolling();return true},
_saveLocal:function(c){localStorage.setItem('sync_roomCode',c);localStorage.setItem('sync_myId',String(this.myId))},
_startPolling:function(){var s=this;if(this.polling)clearInterval(this.polling);s._poll();this.polling=setInterval(function(){s._poll()},2500)},
_poll:function(){var s=this;var q='room_code=eq.'+encodeURIComponent(s.roomCode);s._get(q,function(rows){if(rows&&rows.length)s._process(rows[0])})},
_process:function(d){var ch=false,pi=this.myId===1?2:1,mk='user'+this.myId+'_',pk='user'+pi+'_';if(d[mk+'mood'])this.myMood=d[mk+'mood'];if(d[pk+'mood']){var pm=d[pk+'mood'];if(!this.partnerMood||this.partnerMood.updatedAt!==pm.updatedAt){this.partnerMood=pm;ch=true}}if(d[pk+'name']&&!localStorage.getItem('sync_partnerName_remote')){localStorage.setItem('sync_partnerName',d[pk+'name'])}if(d.messages&&d.messages.length){var nc=0;for(var i=0;i<d.messages.length;i++){var m=d.messages[i];if(m.sender===pi){var ex=this.partnerMessages.some(function(x){return x.createdAt===m.createdAt});if(!ex){this.partnerMessages.unshift(m);nc++}}}if(nc>0){this.partnerMessages.sort(function(a,b){return new Date(b.createdAt)-new Date(a.createdAt)});ch=true}}if(ch&&this.onChange)this.onChange('mood')},
updateMood:function(st){var s=this;var q='room_code=eq.'+encodeURIComponent(s.roomCode);s._get(q,function(rows){if(!rows||!rows.length)return;var d=rows[0];var mk='user'+s.myId+'_';d[mk+'mood']={status:st,updatedAt:new Date().toISOString()};s.myMood=d[mk+'mood'];s._patch(d.id,d)})},
sendMessage:function(t,dd,mo){var s=this;return new Promise(function(r){var q='room_code=eq.'+encodeURIComponent(s.roomCode);s._get(q,function(rows){if(!rows||!rows.length){r({error:'failed'});return}var d=rows[0];if(!d.messages)d.messages=[];d.messages.push({sender:s.myId,text:t||'',doodleDataUrl:dd||null,mood:mo||'sunny',createdAt:new Date().toISOString()});if(d.messages.length>100)d.messages=d.messages.slice(-100);s._patch(d.id,d,function(){r({success:true})})})})},
_get:function(q,cb){var x=new XMLHttpRequest();x.open('GET',this.BASE+'?'+q+'&order=id.asc',true);x.setRequestHeader('apikey',this.KEY);x.setRequestHeader('Authorization','Bearer '+this.KEY);x.timeout=8000;x.onload=function(){if(x.status===200){try{cb(JSON.parse(x.responseText))}catch(e){cb(null)}}else{cb(null)}};x.onerror=function(){cb(null)};x.send()},
_post:function(d,cb){var x=new XMLHttpRequest();x.open('POST',this.BASE,true);x.setRequestHeader('apikey',this.KEY);x.setRequestHeader('Authorization','Bearer '+this.KEY);x.setRequestHeader('Content-Type','application/json');x.setRequestHeader('Prefer','return=representation');x.timeout=8000;x.onload=function(){if(x.status===201){try{var r=JSON.parse(x.responseText);if(cb)cb(r[0])}catch(e){if(cb)cb(d)}}else{if(cb)cb(d)}};x.onerror=function(){if(cb)cb(d)};x.send(JSON.stringify(d))},
_patch:function(id,d,cb){var x=new XMLHttpRequest();x.open('PATCH',this.BASE+'?id=eq.'+id,true);x.setRequestHeader('apikey',this.KEY);x.setRequestHeader('Authorization','Bearer '+this.KEY);x.setRequestHeader('Content-Type','application/json');x.timeout=8000;x.onload=function(){if(cb)cb()};x.onerror=function(){if(cb)cb()};x.send(JSON.stringify(d))},
leave:function(){if(this.polling)clearInterval(this.polling);localStorage.removeItem('sync_roomCode');localStorage.removeItem('sync_myId');this.roomCode=null;this.myId=null}};
