// UUID
function generateId(){return'xxxx-xxxx-xxxx'.replace(/x/g,function(){return Math.floor(Math.random()*16).toString(16)})}
// Date helpers
function formatDate(s){var d=new Date(s),n=new Date(),t=new Date(n.getFullYear(),n.getMonth(),n.getDate()),e=new Date(d.getFullYear(),d.getMonth(),d.getDate()),i=Math.floor((t-e)/864e5);if(i===0)return'今天';if(i===1)return'昨天';if(i===2)return'前天';if(i<7)return i+'天前';return d.getFullYear()+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+String(d.getDate()).padStart(2,'0')}
function formatTime(s){var d=new Date(s);return String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}
function formatDateFull(s){return formatDate(s)+' '+formatTime(s)}
function groupByDate(a){var g={};a.forEach(function(e){var k=formatDate(e.createdAt);if(!g[k])g[k]=[];g[k].push(e)});return g}
function escapeHtml(t){var d=document.createElement('div');d.textContent=t;return d.innerHTML}
function $(s){return document.querySelector(s)}
function $$(s){return document.querySelectorAll(s)}
function showToast(m,d){if(!d)d=2000;var t=$('#toast');if(!t)return;t.textContent=m;t.classList.remove('hidden');requestAnimationFrame(function(){t.classList.add('show')});setTimeout(function(){t.classList.remove('show');setTimeout(function(){t.classList.add('hidden')},300)},d)}
// Mood config
var MOOD_CONFIG={sunny:{icon:'☀️',label:'晴朗'},cloudy:{icon:'☁️',label:'多云'},rainy:{icon:'🌧️',label:'雨天'},storm:{icon:'⛈️',label:'雷暴'},love:{icon:'❤️',label:'爱心'},dnd:{icon:'🔕',label:'勿扰'}};
// Global helpers
function getMyCode(){var c=localStorage.getItem('my_pair_code');if(!c){c='';var ch='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';for(var i=0;i<6;i++)c+=ch[Math.floor(Math.random()*ch.length)];localStorage.setItem('my_pair_code',c)}return c}
function copyMyCode(){var c=getMyCode();if(navigator.clipboard){navigator.clipboard.writeText(c).then(function(){var el=document.getElementById('copy-hint');if(el){el.style.display='block';setTimeout(function(){el.style.display='none'},1500)}})}else{prompt('长按复制：',c)}}
function goRoomStep(){var i=document.getElementById('auth-name');if(!i)return;var n=i.value.trim();if(!n){showToast('请输入TA的昵称',1500);return}localStorage.setItem('sync_partnerName',n);document.getElementById('auth-step-name').classList.add('hidden');document.getElementById('auth-step-room').classList.remove('hidden');document.getElementById('my-pair-code').textContent=getMyCode();document.getElementById('auth-error').textContent=''}
function goNameStep(){document.getElementById('screen-auth').style.display='flex';document.getElementById('auth-step-name').classList.remove('hidden');document.getElementById('auth-step-room').classList.add('hidden')}
function doJoin(){var i=document.getElementById('auth-code');if(!i)return;var c=i.value.trim();if(!c){document.getElementById('auth-error').textContent='请输入TA的配对码';return}if(c===getMyCode()){document.getElementById('auth-error').textContent='不能输入自己的配对码';return}document.getElementById('auth-error').textContent='';document.getElementById('auth-step-room').classList.add('hidden');document.getElementById('screen-auth').style.display='none';document.getElementById('app').classList.remove('hidden');var codes=[getMyCode(),c].sort();var room=codes[0]+'-'+codes[1];localStorage.setItem('sync_roomCode',room);if(typeof Sync!=='undefined')Sync.joinRoom(room,'我');var t=0;function chk(){t++;if(typeof Sync!=='undefined'&&Sync.myId){if(typeof App!=='undefined'&&App.showApp)App.showApp();return}if(t<40)setTimeout(chk,500);else{if(typeof App!=='undefined'&&App.showApp)App.showApp()}}setTimeout(chk,1000)}
function pickMood(s){var c=MOOD_CONFIG[s]||MOOD_CONFIG.sunny;var d={status:s,updatedAt:new Date().toISOString(),message:''};try{localStorage.setItem('moodState_me',JSON.stringify(d))}catch(e){}if(typeof Sync!=='undefined'&&Sync.roomCode)Sync.updateMood(s);var ie=document.getElementById('mood3d-icon');var le=document.getElementById('mood3d-label');if(ie)ie.textContent=c.icon;if(le)le.textContent=c.label;var os=document.querySelectorAll('.mood3d-opt');for(var i=0;i<os.length;i++){if(os[i].getAttribute('data-mood')===s)os[i].classList.add('selected');else os[i].classList.remove('selected')}if(navigator.vibrate)navigator.vibrate(8);showToast('已更新 '+c.icon,1500)}
function pickSendMood(m){if(typeof Send!=='undefined')Send.sendMood=m;var bs=document.querySelectorAll('#send-mood-select .mood-stamp-btn');for(var i=0;i<bs.length;i++){if(bs[i].getAttribute('data-mood')===m)bs[i].classList.add('selected');else bs[i].classList.remove('selected')}}
function editPartnerName(){var c=localStorage.getItem('sync_partnerName')||'TA';var n=prompt('输入TA的称呼：',c);if(n&&n.trim()){localStorage.setItem('sync_partnerName',n.trim());try{var s=getSettings('ta');s.profileName=n.trim();saveSettings(s,'ta')}catch(e){}if(typeof Weather!=='undefined')Weather.refresh();if(typeof TreeHole!=='undefined')TreeHole.refresh()}}
function leaveAndReset(){if(confirm('确定退出吗？')){if(typeof Sync!=='undefined')Sync.leave();localStorage.removeItem('sync_partnerName');document.getElementById('app').classList.add('hidden');goNameStep()}}
function clearAllData(){if(confirm('确定清除本地数据吗？')){localStorage.clear();location.reload()}}
